name: responsive_login_ui
description: Responsive SignUp & Login Screens

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.0
  lottie: ^1.4.2
  http: ^0.13.0
  firebase_auth: ^3.11.0
  shared_preferences: ^2.0.15
  modal_bottom_sheet: ^2.1.2
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.1
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo+texto.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
